name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel_version }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        bazel_version: [bazelbuild/6.5.0, bazelbuild/7.2.1]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-version: 1.20.0
      - run: cat .bazelrc.ci >> .bazelrc
      - run: ./scripts/format.sh check
      - run: ./test/run_all_tests.sh ci
      - run: ./scripts/gen-docs.sh && git diff --exit-code docs/
      - run: bazel shutdown
